/**
 * API Endpoint: /api/submit
 * Purpose: Send trade package to trades desk via email
 */

import formidable from 'formidable';
import fs from 'fs';
import sgMail from '@sendgrid/mail';

// Disable body parser for file uploads
export const config = {
  api: {
    bodyParser: false,
  },
};

// Initialize SendGrid
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

/**
 * Generate HTML email template
 */
function generateEmailHTML(data) {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #0F172A; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { background: #f8f9fa; padding: 20px; border: 1px solid #e0e0e0; }
    .section { margin-bottom: 20px; background: white; padding: 15px; border-radius: 8px; }
    .section-title { font-weight: bold; color: #0F172A; margin-bottom: 10px; font-size: 18px; }
    .field { margin: 8px 0; }
    .label { font-weight: 600; color: #64748B; }
    .value { color: #0F172A; }
    .footer { background: #0F172A; color: white; padding: 15px; text-align: center; border-radius: 0 0 8px 8px; font-size: 14px; }
    .badge { display: inline-block; padding: 4px 12px; background: #10B981; color: white; border-radius: 12px; font-size: 14px; font-weight: 600; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📋 New Trade Submission</h1>
      <span class="badge">${data.transactionType === 'seller' ? '📤 SELLER' : '📥 BUYER'}</span>
    </div>
    
    <div class="content">
      <div class="section">
        <div class="section-title">🏡 Property Information</div>
        <div class="field"><span class="label">Address:</span> <span class="value">${data.propertyAddress || 'N/A'}</span></div>
        <div class="field"><span class="label">City:</span> <span class="value">${data.city || 'N/A'}</span></div>
        <div class="field"><span class="label">Closing Date:</span> <span class="value">${data.closingDate || 'N/A'}</span></div>
        <div class="field"><span class="label">${data.transactionType === 'seller' ? 'List Price' : 'Offer Price'}:</span> <span class="value">${data.listPrice || 'N/A'}</span></div>
        <div class="field"><span class="label">Sale Price:</span> <span class="value">${data.salePrice || 'N/A'}</span></div>
      </div>

      <div class="section">
        <div class="section-title">👤 ${data.transactionType === 'seller' ? 'Seller' : 'Buyer'} Information</div>
        <div class="field"><span class="label">Name:</span> <span class="value">${data.clientName || 'N/A'}</span></div>
        <div class="field"><span class="label">Phone:</span> <span class="value">${data.clientPhone || 'N/A'}</span></div>
        <div class="field"><span class="label">Email:</span> <span class="value">${data.clientEmail || 'N/A'}</span></div>
      </div>

      <div class="section">
        <div class="section-title">⚖️ Solicitor Information</div>
        <div style="margin-bottom: 15px;">
          <strong>Seller's Solicitor:</strong><br>
          <div class="field"><span class="label">Name:</span> <span class="value">${data.sellerSolicitorName || 'N/A'}</span></div>
          <div class="field"><span class="label">Firm:</span> <span class="value">${data.sellerSolicitorFirm || 'N/A'}</span></div>
          <div class="field"><span class="label">Phone:</span> <span class="value">${data.sellerSolicitorPhone || 'N/A'}</span></div>
          <div class="field"><span class="label">Email:</span> <span class="value">${data.sellerSolicitorEmail || 'N/A'}</span></div>
        </div>
        <div>
          <strong>Buyer's Solicitor:</strong><br>
          <div class="field"><span class="label">Name:</span> <span class="value">${data.buyerSolicitorName || 'N/A'}</span></div>
          <div class="field"><span class="label">Firm:</span> <span class="value">${data.buyerSolicitorFirm || 'N/A'}</span></div>
          <div class="field"><span class="label">Phone:</span> <span class="value">${data.buyerSolicitorPhone || 'N/A'}</span></div>
          <div class="field"><span class="label">Email:</span> <span class="value">${data.buyerSolicitorEmail || 'N/A'}</span></div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">📎 Attached Documents</div>
        <div class="field">Number of files: <strong>${data.fileCount || 0}</strong></div>
        <div class="field">Submitted by: <strong>${data.agentEmail || 'N/A'}</strong></div>
        <div class="field">Submission time: <strong>${new Date().toLocaleString()}</strong></div>
      </div>
    </div>
    
    <div class="footer">
      Generated by Trade Record Generator | Sutton Group Realty Systems Inc.
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * Generate confirmation email for agent
 */
function generateConfirmationHTML(data) {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #10B981; color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { background: #f8f9fa; padding: 30px; border: 1px solid #e0e0e0; text-align: center; }
    .checkmark { font-size: 64px; margin-bottom: 20px; }
    .message { font-size: 18px; margin-bottom: 20px; color: #0F172A; }
    .details { background: white; padding: 20px; border-radius: 8px; margin-top: 20px; text-align: left; }
    .footer { background: #0F172A; color: white; padding: 15px; text-align: center; border-radius: 0 0 8px 8px; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Trade Submitted Successfully!</h1>
    </div>
    
    <div class="content">
      <div class="checkmark">✅</div>
      <div class="message">
        Your ${data.transactionType === 'seller' ? 'seller' : 'buyer'} trade has been submitted to the trades desk.
      </div>
      
      <div class="details">
        <p><strong>Property:</strong> ${data.propertyAddress || 'N/A'}</p>
        <p><strong>Files Submitted:</strong> ${data.fileCount || 0}</p>
        <p><strong>Submission Time:</strong> ${new Date().toLocaleString()}</p>
        <p style="margin-top: 20px; color: #64748B; font-size: 14px;">
          The trades desk will process your submission and reach out if any additional information is needed.
        </p>
      </div>
    </div>
    
    <div class="footer">
      Trade Record Generator | Sutton Group Realty Systems Inc.
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * Main handler
 */
export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    // Parse form data with files
    const form = formidable({
      maxFileSize: 50 * 1024 * 1024, // 50MB total
      maxFiles: 20,
    });

    const [fields, files] = await new Promise((resolve, reject) => {
      form.parse(req, (err, fields, files) => {
        if (err) reject(err);
        resolve([fields, files]);
      });
    });

    // Extract form data
    const formData = {};
    Object.keys(fields).forEach(key => {
      formData[key] = fields[key]?.[0] || '';
    });

    const uploadedFiles = files.files || [];
    const fileArray = Array.isArray(uploadedFiles) ? uploadedFiles : [uploadedFiles];

    // Prepare attachments for email
    const attachments = fileArray.map(file => ({
      content: fs.readFileSync(file.filepath).toString('base64'),
      filename: file.originalFilename,
      type: file.mimetype,
      disposition: 'attachment'
    }));

    // Email to Trades Desk
    const tradeDeskEmail = {
      to: process.env.TRADES_DESK_EMAIL || formData.tradesDeskEmail || 'trades@suttonstore.com',
      from: {
        email: 'sbulatovic@sutton.com',
        name: 'Trade Record Generator'
      },
      subject: `New ${formData.transactionType === 'seller' ? 'Seller' : 'Buyer'} Trade: ${formData.propertyAddress || 'No Address'}`,
      html: generateEmailHTML({
        ...formData,
        fileCount: fileArray.length
      }),
      attachments: attachments
    };

    // Add CC if provided
    if (formData.ccEmails) {
      const ccList = formData.ccEmails.split(',').map(email => email.trim()).filter(Boolean);
      if (ccList.length > 0) {
        tradeDeskEmail.cc = ccList;
      }
    }

    // Confirmation email to agent
    const confirmationEmail = {
      to: formData.agentEmail,
      from: {
        email: 'sbulatovic@sutton.com',
        name: 'Trade Record Generator'
      },
      subject: '✅ Trade Submission Confirmation',
      html: generateConfirmationHTML({
        ...formData,
        fileCount: fileArray.length
      })
    };

    // Send both emails
    await Promise.all([
      sgMail.send(tradeDeskEmail),
      sgMail.send(confirmationEmail)
    ]);

    // Clean up temp files
    fileArray.forEach(file => {
      try {
        fs.unlinkSync(file.filepath);
      } catch (e) {
        console.error('Failed to delete temp file:', e);
      }
    });

    return res.status(200).json({
      success: true,
      message: 'Trade submitted successfully',
      filesSubmitted: fileArray.length
    });

  } catch (error) {
    console.error('Submission error:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to submit trade',
      message: error.message
    });
  }
}
